# Generated by Django 3.0.6 on 2020-06-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_slideimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideimages',
            old_name='image',
            new_name='images',
        ),
    ]
