# Generated by Django 3.0.6 on 2020-06-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200605_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideimages',
            old_name='images',
            new_name='image',
        ),
    ]
