# Generated by Django 3.0.6 on 2020-06-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200605_0840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideImages',
            new_name='SlideImage',
        ),
    ]
