# Generated by Django 3.0.6 on 2020-06-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200605_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideimage',
            old_name='name',
            new_name='img_name',
        ),
    ]
