# Generated by Django 3.0.6 on 2020-06-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200605_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slideimage',
            old_name='img_name',
            new_name='name',
        ),
    ]
